language: node_js

git:
  depth: 5

before_install:
  # show product version
  - npm i -g npm@latest
  - nvm --version
  - node --version
  - npm --version

install:
  - npm ci
  - npm run build:dev

jobs:
  include:
    - state: "Test"
      name: "Unit Test Node v12"
      script: npm test
      node_js: 12
      # after_success: npm run coverage

    - state: "Test"
      name: "Unit Test Node v10"
      script: npm test
      node_js: 10

    - state: "Test"
      name: "Unit Test Node v8"
      script: npm test
      node_js: 8

    - stage: "Test"
      name: "Lint"
      script: npm run lint
      node_js: 12
